# Generated by Django 2.1.5 on 2019-01-06 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190106_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='activity',
        ),
        migrations.AddField(
            model_name='activity',
            name='member',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Member', verbose_name='Member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='sex',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=200, null=True),
        ),
    ]
