# Generated by Django 2.1.5 on 2019-01-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190106_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='member',
        ),
        migrations.AddField(
            model_name='member',
            name='activity',
            field=models.ManyToManyField(to='core.Activity'),
        ),
    ]
