# Generated by Django 2.1.5 on 2019-01-13 20:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Number')),
                ('ticket_id', models.CharField(max_length=255, verbose_name='Ticket ID')),
                ('qr_code', models.CharField(max_length=255, verbose_name='QR Code')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is paid')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Start Date'),
        ),
        migrations.AddField(
            model_name='event',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.Ticket', verbose_name='Ticket'),
        ),
    ]
