# Generated by Django 2.1.5 on 2019-01-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_participant_ticket_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='ticket_num',
            new_name='ticket',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='qr_code',
            field=models.ImageField(default='qr_images/None/no-qr.jpg', upload_to='qr_images/', verbose_name='QR Code'),
        ),
    ]
