# Generated by Django 2.1.5 on 2019-01-20 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20190120_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='ticket',
            new_name='tickets',
        ),
    ]
